import argparse
import os

import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import nibabel as nib
import numpy as np


TUMOUR_CLASS = 1
TUMOUR_CMAP = mcolors.ListedColormap([(1.0, 0.15, 0.15, 0.75)])


def parse_args():
    """Parse paths and rendering options from the command line."""
    parser = argparse.ArgumentParser(
        description='Render low-Dice NIfTI triplets into one PNG.'
    )
    parser.add_argument(
        'sample_list',
        help='Path to low_dice_sample.txt generated by test_2d.py',
    )
    parser.add_argument(
        '--output',
        default=None,
        help='Output PNG path (default: next to the sample list)',
    )
    parser.add_argument('--dpi', type=int, default=150)
    parser.add_argument(
        '--max-samples',
        type=int,
        default=30,
        help='Maximum number of randomly selected samples to render',
    )
    parser.add_argument(
        '--seed',
        type=int,
        default=1234,
        help='Random seed used for reproducible sample selection',
    )
    return parser.parse_args()


def load_sample_paths(sample_list):
    """Load image paths while preserving the inference order."""
    if not os.path.isfile(sample_list):
        raise FileNotFoundError(f'Sample list does not exist: {sample_list}')

    paths = []
    with open(sample_list, 'r', encoding='utf-8') as file:
        for line_number, line in enumerate(file, start=1):
            gt_path = line.strip()
            if not gt_path:
                continue
            if not gt_path.endswith('_gt.nii.gz'):
                raise ValueError(
                    f'Line {line_number} is not an *_gt.nii.gz path: {gt_path}'
                )
            paths.append(gt_path)
    return paths


def get_triplet_paths(gt_path):
    """Derive the image and prediction paths from a ground-truth path."""
    prefix = gt_path[: -len('_gt.nii.gz')]
    return f'{prefix}_img.nii.gz', gt_path, f'{prefix}_pred.nii.gz'


def load_2d_nifti(path):
    """Load a NIfTI slice and reject volumes with more than one real slice."""
    if not os.path.isfile(path):
        raise FileNotFoundError(f'NIfTI file does not exist: {path}')
    data = np.asarray(nib.load(path).get_fdata())
    data = np.squeeze(data)
    if data.ndim != 2:
        raise ValueError(f'Expected a 2D slice after squeezing, got {data.shape}: {path}')
    return data


def normalize_image(image):
    """Normalize one CT slice to [0, 1] for stable display."""
    finite = np.isfinite(image)
    if not np.any(finite):
        return np.zeros_like(image, dtype=np.float32)
    low, high = np.percentile(image[finite], (1, 99))
    if high <= low:
        return np.zeros_like(image, dtype=np.float32)
    return np.clip((image - low) / (high - low), 0.0, 1.0)


def tumour_dice(gt, pred):
    """Compute the tumour Dice score shown in the row label."""
    gt_mask = gt == TUMOUR_CLASS
    pred_mask = pred == TUMOUR_CLASS
    denominator = gt_mask.sum() + pred_mask.sum()
    if denominator == 0:
        return 1.0
    return 2.0 * np.logical_and(gt_mask, pred_mask).sum() / denominator


def draw_overlay(axis, image, mask):
    """Draw a grayscale slice with a red tumour overlay."""
    axis.imshow(image, cmap='gray', vmin=0.0, vmax=1.0)
    tumour_mask = mask == TUMOUR_CLASS
    axis.imshow(
        np.ma.masked_where(~tumour_mask, tumour_mask),
        cmap=TUMOUR_CMAP,
        vmin=0,
        vmax=1,
    )
    axis.axis('off')


def select_random_samples(paths, max_samples, seed):
    """Select a reproducible subset without replacement."""
    if max_samples <= 0:
        raise ValueError(f'--max-samples must be positive, got: {max_samples}')
    if len(paths) <= max_samples:
        return paths

    random_generator = np.random.default_rng(seed)
    selected_indices = random_generator.choice(
        len(paths), size=max_samples, replace=False
    )
    return [paths[index] for index in selected_indices]


def visualize_samples(sample_list, output_path, dpi=150, max_samples=30, seed=1234):
    """Render a random subset of listed NIfTI triplets into one PNG."""
    gt_paths = load_sample_paths(sample_list)
    if not gt_paths:
        raise ValueError(f'No low-Dice samples were listed in: {sample_list}')
    total_samples = len(gt_paths)
    gt_paths = select_random_samples(gt_paths, max_samples, seed)

    figure, axes = plt.subplots(
        len(gt_paths),
        3,
        figsize=(12, 3.6 * len(gt_paths)),
        squeeze=False,
    )
    for row, gt_path in enumerate(gt_paths):
        image_path, gt_path, pred_path = get_triplet_paths(gt_path)
        image = load_2d_nifti(image_path)
        gt = load_2d_nifti(gt_path)
        pred = load_2d_nifti(pred_path)
        if image.shape != gt.shape or image.shape != pred.shape:
            raise ValueError(
                f'Shape mismatch for {image_path}: '
                f'image={image.shape}, gt={gt.shape}, pred={pred.shape}'
            )

        display_image = normalize_image(image)
        axes[row, 0].imshow(display_image, cmap='gray', vmin=0.0, vmax=1.0)
        axes[row, 0].axis('off')
        draw_overlay(axes[row, 1], display_image, gt)
        draw_overlay(axes[row, 2], display_image, pred)
        sample_name = os.path.basename(image_path)[: -len('_img.nii.gz')]
        axes[row, 0].set_ylabel(
            f'{sample_name}\nDice={tumour_dice(gt, pred):.3f}',
            rotation=0,
            ha='right',
            va='center',
        )

    for column, title in enumerate(('CT image', 'Tumour GT', 'Tumour prediction')):
        axes[0, column].set_title(title, fontsize=13, fontweight='bold')

    output_dir = os.path.dirname(os.path.abspath(output_path))
    os.makedirs(output_dir, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=dpi, bbox_inches='tight')
    plt.close(figure)
    print(
        f'Saved {len(gt_paths)} randomly selected samples '
        f'from {total_samples} low-Dice samples to: {output_path}'
    )


def main():
    """Run the low-Dice visualization command."""
    args = parse_args()
    output_path = args.output
    if output_path is None:
        output_path = os.path.join(
            os.path.dirname(os.path.abspath(args.sample_list)),
            'low_dice_samples.png',
        )
    visualize_samples(
        args.sample_list,
        output_path,
        dpi=args.dpi,
        max_samples=args.max_samples,
        seed=args.seed,
    )


if __name__ == '__main__':
    main()
